schema_version = "1.0.0"

id = "blenderkitty"
version = "2.0.1"
name = "blenderkitty"
tagline = "Lower your productivity immensely with cute kitten technology"
maintainer = "polygoniq <ahoy@polygoniq.com>"
type = "add-on"

permissions = ["files", "network"]
tags = ["User Interface"]
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2018- polygoniq xyz s.r.o",
]